title: Innovation Guides
url: "http://guides.austintexas.io" # the base hostname & protocol for your site

theme: jekyll-theme-zilker

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

collections:
  developer-guide:
    title: Developer Guide
    output: true
