---
title: Innovation Guides
timezone: UTC
collections:
  developer-guide:
    title: Developer Guide
    output: true
  github-pages:
    title: GitHub Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
url: http://guides.austintexas.io
theme: jekyll-theme-zilker
permalink: pretty
